CREATE TABLE T_PRODUCT_CATEGORY (
    ID NUMBER(38) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_ID_PRODUCT_CATEGORY PRIMARY KEY (ID)
);

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE T_PRODUCT_STORED (
    ID NUMBER(38) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    PRICE NUMBER(38,2) NOT NULL,
    QUANTITY NUMBER(38) NOT NULL,
    FK_CATEGORY NUMBER(38) NOT NULL,
    CONSTRAINT PK_ID_PRODUCT_STORED PRIMARY KEY (ID),
    CONSTRAINT FK_CATEGORY_PRODUCT_STORED FOREIGN KEY (FK_CATEGORY) REFERENCES T_PRODUCT_CATEGORY(ID)
);
